runtime: nodejs18

env_variables:
  DATABASE_HOST: "35.189.96.189"
  DATABASE_PORT: 3306
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "X@HcgA5@R}R3o#5;"
  DATABASE_NAME: "grotrackdb"
  SECRETKEY: :GroTrack2023"
  EXPIRESIN: "600s"
  INSTANCE-REGION: "europe-west2"
  INSTANCE-NAME: "grotrack-db"
  MY-PROJECT: "grotrack-app"

services: grotrackserver